
version: '3.4'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  todoitemsmongodbapiapi:
    image: todoitemsmongodbapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mongodb